/* ecuconst.h
 * version 0.1
 * By: M.J. Camara
 * Defines the constants used frequently for the EigenCU program
 */
// Width of training and incoming images
#define IMG_WIDTH 178
// Threshold determining eligible face class score
#define FC_THRES 6000
// Threshold determining eligible face space score
// 5500 might be the new threshold in the future
#define FS_THRES 8000
// Total # of eigenfaces generated by the algorithm
#define TOTAL_EIG 35